spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

  datasource:
<<<<<<< Updated upstream
    url: jdbc:mysql://${DB_URL}/dsm_gg
=======
    url: jdbc:mysql://${DB_URL}/dsm_gg?&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
>>>>>>> Stashed changes
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}


jwt:
  secret-key: ${JWT_SECRET}
  access-exp: ${JWT_ACCESS_EXP}
  refresh-exp: ${JWT_REFRESH_EXP}
  header: ${JWT_HEADER}
  prefix: ${JWT_PREFIX}

logging:
  level:
    root: info


server:
  tomcat:
    connection-timeout: -1

riot:
  api-key = ${RIOT_API_KEY}
